### ISSUE TITLE
Issue with mysql table setup

### ISSUE THREAD

**Issue by harryjxu** [jburns20/q#9]
setup according to README, getting this 

'Unhandled rejection SequelizeDatabaseError: ER_NO_SUCH_TABLE: Table 'queue.options' doesn't exist
    at Query.formatError (/Users/harryxu/Desktop/Harrys_Stuff/School/Carnegie_Mellon_Undergrad/q/node_modules/sequelize/lib/dialects/mysql/query.js:175:14)
    at Query._callback (/Users/harryxu/Desktop/Harrys_Stuff/School/Carnegie_Mellon_Undergrad/q/node_modules/sequelize/lib/dialects/mysql/query.js:49:21)
    at Query.Sequence.end (/Users/harryxu/Desktop/Harrys_Stuff/School/Carnegie_Mellon_Undergrad/q/node_modules/mysql/lib/protocol/sequences/Sequence.js:88:24)
    at Query.ErrorPacket (/Users/harryxu/Desktop/Harrys_Stuff/School/Carnegie_Mellon_Undergrad/q/node_modules/mysql/lib/protocol/sequences/Query.js:90:8)
    at Protocol._parsePacket (/Users/harryxu/Desktop/Harrys_Stuff/School/Carnegie_Mellon_Undergrad/q/node_modules/mysql/lib/protocol/Protocol.js:279:23)
    at Parser.write (/Users/harryxu/Desktop/Harrys_Stuff/School/Carnegie_Mellon_Undergrad/q/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/Users/harryxu/Desktop/Harrys_Stuff/School/Carnegie_Mellon_Undergrad/q/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/Users/harryxu/Desktop/Harrys_Stuff/School/Carnegie_Mellon_Undergrad/q/node_modules/mysql/lib/Connection.js:103:28)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:607:20)'

**Comment by jburns20** [comment]
Resolved in most recent update.
